---
- hosts: all
  user: vagrant
  sudo: true
  sudo_user: root

  roles:
    - role: ansible-nginx
    - role: ansible-softwares
    - role: ansible-nodejs
    - role: ansible-postgresql
    # - role: ansible-nodejs-apps
      # apps:
      #   enabled:
      #     - "/srv/pto-tracker/"
